config/routes.rb
TaskTime::Application.routes.draw do
  get "pages/home"
  post "tasks/start"
  post "tasks/stop"

  root :to => "pages#home"
  
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :running, :start_time, :stop_time, :total_time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @tasks = Task.all    
  end  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(params[:task])
    
    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: "Task was successfully created." }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to root_path, notice: "Task was successfully updated." }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    
    respond_to do |format|
      format.html { redirect_to root_path, notice: "#{@task.title} has been deleted." }
    end
  end
  
  def start
    task = Task.find(params[:id])
    running_task = Task.where(:running => true)
    message = ""
    if running_task == []
      task.start_time = DateTime.now
      task.running = true
      task.save!
      message = "'#{task.name}' started."
    else
      message = "'#{running_task[0].name}' is already running!"
    end
    
    respond_to do |format|
     format.html { redirect_to root_path, notice: "#{message}" }
    end
  end
  
  def stop
    task = Task.find(params[:id])
    task.running = false
    task.stop_time = DateTime.now
    time_elapsed = task.stop_time - task.start_time
    task.total_time = task.total_time + time_elapsed
    task.save!
    
    respond_to do |format|
     format.html { redirect_to root_path, notice: "'#{task.name}' stopped." }
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def parse_total_time(time)
    # skipping the modulus for speed
    if time < 60
      "#{time} seconds"
    elsif time < 3600
      "#{(time/60.0).round} minutes"
    else
      "#{(time/3600.0).round(1)} hours"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskTime</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p id="notice"><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Task Timer</h1>
<hr>
<% @tasks.each do |task| %>
  <p><%= task.name %> (<%= parse_total_time(task.total_time) %>)
		<% if task.running != true %>
	    <%= button_to "Start", tasks_start_path(:id => task.id), :class => "start" %>
		<% else %>
		  <%= button_to "Stop", tasks_stop_path(:id => task.id), :class => "stop" %>
		<% end %>
	</p>
	<hr>
<% end %>

<%= link_to "Add a task", new_task_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %><br/>
  <%= f.text_field :name %><br/>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit "<%= @task.name %>"</h1>

<%= render 'form' %>

<%= link_to "Home", root_path %>

app/views/tasks/new.html.erb
<h1>Create a task</h1>

<%= render 'form' %>

<%= link_to "Home", root_path %>